apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abstergo-web
  template:
    metadata:
      labels:
        app: abstergo-web
    spec:
      containers:
      - name: abstergo-web
        image: ashishdocker02/abstergo-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abstergo-web-service
spec:
  selector:
    app: abstergo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
