apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abstergo-web
  template:
    metadata:
      labels:
        app: abstergo-web
    spec:
      containers:
      - name: abstergo-web
        image: ashishdocker02/abstergo-web:latest
        ports:
        - containerPort: 80
